### ISSUE TITLE
oemof package ignores required pypi packages

### ISSUE THREAD

**Issue by gplssm** [oemof/oemof#76]
Upgrading to oemof 0.0.3 involved upgrade of pandas (from 0.16.2 to 0.17.1).

I did the following
- `git clone git@github.com:oemof/oemof.git`
- `sudo pip3 install -e oemof`

oemof installed well, subsequent installation of pandas 0.17.1 failed  and rolled back to previous version 0.16.2.

I'm not sure if this is really an issue to oemof or more to pypi itself. Nevertheless, installing oemof otting some defined required pypi package is obviously a misbehaviour!

Here some logging:

```
creating build/temp.linux-x86_64-3.4/pandas
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -Ipandas/src/klib -Ipandas/src -I/usr/local/lib/python3.4/dist-packages/numpy/core/include -I/usr/include/python3.4m -c pandas/hashtable.c -o build/temp.linux-x86_64-3.4/pandas/hashtable.o

pandas/hashtable.c:4:20: fatal error: Python.h: Datei oder Verzeichnis nicht gefunden

 #include "Python.h"
                    ^
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
----------------------------------------
  Rolling back uninstall of pandas
Cleaning up...
Command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/pandas/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-_steb8x7-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/pandas
Storing debug log for failure in /home/guido/.pip/pip.log```

**Comment by ckaldemeyer** [comment]
Can you check if the storage_invest examples is running? The newer pandas version is required for the dataframe MultiIndex functionality in the outputlib so I changed the requirement to the newest version. But maybe it already works with 0.16.*..

**Comment by ckaldemeyer** [comment]
The important part is that the Plotting/DataFrame-Slicing should work

**Comment by gplssm** [comment]
Different, but not working, see:

```
guido@pc-12:~/home/git-repos/oemof/examples/storage_optimization$ python3 storage_invest.py 
Traceback (most recent call last):
  File "storage_invest.py", line 38, in <module>
    from oemof.solph import predefined_objectives as predefined_objectives
  File "/home/guido/home/git-repos/oemof/oemof/solph/predefined_objectives.py", line 13, in <module>
    import pyomo.environ as po
ImportError: No module named 'pyomo'
```

Shouldn't be pyomo a depency of oemof?

**Comment by ckaldemeyer** [comment]
Yep, it should be! Something obviously went wrong

**Comment by ckaldemeyer** [comment]
I'll have a look at it

**Comment by gplssm** [comment]
Thanks! Meanwhile I'll try to fix my package management issues with pypi...

**Comment by ckaldemeyer** [comment]
Weird, the setup.py looks  o.k. to me:

#! /usr/bin/env python

	"""TODO: Maybe add a docstring containing a long description for oemof?
	  This would double as something we could put int the `long_description`
	  parameter for `setup` and it would squelch some complaints pylint has on
	  `setup.py`.
	"""

	from setuptools import find_packages, setup

	import oemof

	setup(name='oemof',
		  version=oemof.__version__,
		  author='oemof developing group',
		  author_email='oemof@rl-institut.de',
		  description='The open energy modelling framework',
		  namespace_package = ['oemof'],
		  packages=find_packages(),
		  package_dir={'oemof': 'oemof'},
		  install_requires=['numpy >= 1.7.0',
		                    'pandas >= 0.17.0',
		                    'pyomo >= 4.2.0']
		 )

**Comment by uvchik** [comment]
As long as solph is the only library that solves problems pyomo should be a requirement.

@gplssm: I think your problem is not an oemof problem but a pandas problem.

Did you try: `sudo pip3 install pandas==0.17.1`

A missing `*.h` file is a sign for a missing `dev` package.

Try: `sudo apt-get install python3-dev`

If it does not help try: `sudo pip3 install nose`

If it still does not work try google :smile:

**Comment by gplssm** [comment]
Other problems occurred, so I did it the hard way: purged pip3, reinstall, afterwards I was able to install pandas (0.17.1). So, no issue of oemof itselfs.
