### ISSUE TITLE
 ImportError: cannot import name '_VarDataWithDomain'

### ISSUE THREAD

**Issue by Konsebast** [oemof/oemof#147]
Hello Again,

since the release of version 0.5 I have again a problem with using oemof. When I try to execute any of the example or test files, I get the following error message:

```python
PS D:\Masterarbeit\160426_oemof\tests> python -m basic_tests.py
D:\Masterarbeit\python\python.exe: Error while finding spec for 'basic_tests.py' (<class  ImportError'>: cannot import name '_VarDataWithDomain')
```

The same error occures with the storage_invest.py example and here:
```python
help> oemof.core.energy_system
problem in oemof.core.energy_system - ImportError: cannot import name '_VarDataWithDomain'
```
I use Python 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 19:28:18) [MSC v.1600 32 bit (Intel)] on win32.

Thank you for your help.

**Comment by simnh** [comment]
I think` _VarDataWithDomain` is related with the pyomo package. Can you use pyomo without any problems? 

I cant reproduce your error on my linux machine. Maybe that's something windows specific...

@gnn do you know?


btw: I would recommend to stick to a version for your MA if you want to make sure that is works, as we are 
restructuring quit a lot so until the end of may.

**Comment by uvchik** [comment]
The command ```sudo pip3 install oemof --upgrad ``` will upgrade oemof but also the related packages such as pyomo, pandas etc.. 

You can try to go back to version 0.0.4 using the following command:

```
sudo pip3 install oemof==0.0.4
```

But if this error is caused by pyomo this won't help. Than you can keep oemof v0.0.5 and go back to an older version of pyomo e.g. 4.2.10784 or 4.3.11323.

```
sudo pip3 install pyomo==4.2.10784
```

I agree with @simnh that you shouldn't update any python package while writing on your MA, except you really need a feature that is part of a newer release.  I speak from personal experience :blush:

**Comment by Konsebast** [comment]
Thank you for your help. Downgrading pyomo worked. I will just stick to oemof 0.5 now.

**Comment by uvchik** [comment]
I got the same error using pyomo 4.3.11377 on Ubuntu 14.04. Everything works fine with pyomo  4.3.11345.

@oemof/oemof : Do not upgrade pyomo to the newest version.

@oemof/oemof-namespace : Shouldn't we update the setup.py? Is it possible to exclude a version? If anybody tries to install oemof he/she will get the newest version of pyomo and this is 4.3.11377 by now.

Workaround: Downgrade pyomo after installing oemof:
```
sudo pip3 install pyomo==4.3.11345
```
@simnh : Do you have an idea what causes this error within pyomo?

**Comment by ckaldemeyer** [comment]
> I got the same error using pyomo 4.3.11377 on Ubuntu 14.04. Everything works fine with pyomo 4.3.11345.
> @oemof/oemof : Do not upgrade pyomo to the newest version.

Nope.

> @oemof/oemof-namespace : Shouldn't we update the setup.py? Is it possible to exclude a version? If anybody tries to install oemof he/she will get the newest version of pyomo and this is 4.3.11377 by now.

+1 for (temporally) updating `setup.py`.

It is possible to [require](http://python-packaging-user-guide.readthedocs.io/en/latest/requirements/) specific versions of packages or a "range of versions". If everybody is fine, I would offer myself to adjust the requirements.

**Comment by uvchik** [comment]
@gnn suggested:
```diff
- pyomo >= 4.2.0
+ pyomo >= 4.2.0, != 4.3.11377
```
>If everybody is fine, I would offer myself to adjust the requirements.

@ckaldemeyer Thank you.

**Comment by ckaldemeyer** [comment]
Should work now. See: https://github.com/oemof/oemof/commit/a7b0a9d6f30df448bcb571a46f9c4145d4adcb97

**Comment by simnh** [comment]
Ok this fixes the bug, but does not solve the problem. I will open an issue for this.
