### ISSUE TITLE
Make oemof Python 3.3 compatible

### ISSUE THREAD

**Issue by gplssm** [oemof/oemof#155]
The comannd `from functools import singledispatch` fails under python3.3 with following error: `ImportError: cannot import name singledispatch`

**Comment by uvchik** [comment]
Re-add Python 3.3 to .travis.yml after fixing.

**Comment by gnn** [comment]
Quick question: to me it looks like `singledispatch` was removed during the solph refactoring, so it should be gone now. That means anything from version 0.1.0 should work under Python 3.3.
Can anybody confirm?

**Comment by uvchik** [comment]
We removed the version 3.3 from Travis CI. You can just make a PR with a changed `.travis.yml` file. If it is ready to merge everything is fine again.

**Comment by simnh** [comment]
singledispatch does not exist in solph anymore...

**Comment by gplssm** [comment]
Since this hangs around for a long time, I would suggest to omit support for python 3.3. Current version is 3.6, if I'm right...

We can put effort elsewhere!

**Comment by ckaldemeyer** [comment]
> Since this hangs around for a long time, I would suggest to omit support for python 3.3. Current version is 3.6, if I'm right...
> 
> We can put effort elsewhere!

:+1:

**Comment by uvchik** [comment]
:+1:

**Comment by uvchik** [comment]
BTW. It should work with 3.3. It's just untested. Let's close it until anybody complains.
